services:
  mongo:
    image: mongo:8.0.4
    container_name: feira_mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./dbdata/db:/data/db
    mem_limit: 512m
    cpu_count: 2
  redis:
    # image: redis:7.2.3
    # image: redis:4.0.14
    image: redis:6
    container_name: feira_redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./dbdata/cache:/data
    mem_limit: 512m
    cpu_count: 0
  # api:
  #   image: feira_api
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: feira_api 
  #   environment:
  #     - PORT=3000
  #     - MONGO_URI=mongodb://root:password@mongo:27017/feiradb?authSource=admin
  #     - REDIS_URI=redis://redis:6379
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379 
  #     - SCHEDULER_ENABLE=0
  #   ports:
  #     - 3000:3000
  #   mem_limit: 512m
  #   cpu_count: 0
  #   depends_on:
  #     - mongo
  #     - redis